# Generated by Django 3.0.6 on 2020-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fir_name', models.CharField(max_length=100)),
                ('sec_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='directors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fir_name', models.CharField(max_length=100)),
                ('sec_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movie_director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='movie_genre',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('rank', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
